export const USER_REGISTER_POST = 'USER_REGISTER_POST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'
export const USER_LOGIN_POST = 'USER_LOGIN_POST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'


export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const USER_CHECKOUT_SUCCESS = 'USER_CHECKOUT_SUCCESS'
export const USER_CHECKOUT_REQUEST = 'USER_CHECKOUT_REQUEST'
export const USER_CHECKOUT_COMPLETE = 'USER_CHECKOUT_COMPLETE'



export const LOGIN_SHOW = 'LOGIN_SHOW'
export const LOGIN_HIDE = 'LOGIN_HIDE'
