export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'

export const FETCH_PRODUCTS_REQUEST_HEADER = 'FETCH_PRODUCTS_REQUEST_HEADER'
export const FETCH_PRODUCTS_SUCCESS_HEADER = 'FETCH_PRODUCTS_SUCCESS_HEADER'
export const FETCH_PRODUCTS_FAILURE_HEADER = 'FETCH_PRODUCTS_FAILURE_HEADER'

export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST'
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'

export const FETCH_COLOR_REQUEST = 'FETCH_COLOR_REQUEST'
export const FETCH_COLOR_SUCCESS = 'FETCH_COLOR_SUCCESS'
export const FETCH_COLOR_FAILURE = 'FETCH_COLOR_FAILURE'

export const FETCH_BYID_REQUEST = 'FETCH_BYID_REQUEST'
export const FETCH_BYID_SUCCESS = 'FETCH_BYID_SUCCESS'
export const FETCH_BYID_FAILURE = 'FETCH_BYID_FAILURE'

export const FETCH_CARD_CATEGORY = 'FETCH_CARD_CATEGORY'
export const FETCH_CARD_CATEGORY_S = 'FETCH_CARD_CATEGORY_S'